server:
  port: 8081
  
spring:
  application:
    name: fun-user-manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fun?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    max-idle: 10
    max-wait: 5000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 50          
    password: 1234
    pool:
      max-idle: 20
      max-wait: -1  

security:
  user:
    name: fun20180817
    password: fun20180817
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:      
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/          
  
  
